# Generated by Django 5.2 on 2025-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_categoria_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='requiere_cambio_clave',
            field=models.BooleanField(default=False),
        ),
    ]
