# Generated by Django 5.2 on 2025-04-06 21:55
from django.db import migrations


def convert_exercise_types(apps, schema_editor):
    Ejercicio = apps.get_model('evaluations', 'Ejercicio')
    
    # Mapeo de tipos antiguos a nuevos
    type_mapping = {
        'opcion_multiple': 'teorico',
        'verdadero_falso': 'teorico',
        'respuesta_corta': 'teorico',
        'desarrollo': 'practico'
    }
    
    for ejercicio in Ejercicio.objects.all():
        if ejercicio.tipo in type_mapping:
            ejercicio.tipo = type_mapping[ejercicio.tipo]
            ejercicio.save()


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(convert_exercise_types),
    ]