# Generated by Django 5.2 on 2025-04-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_convert_exercise_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='contenido',
            field=models.JSONField(blank=True, help_text='Contenido del ejercicio en formato JSON', null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('practico', 'Práctico'), ('teorico', 'Teórico')], max_length=20),
        ),
    ]
