# Generated by Django 5.2 on 2025-04-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_ejercicio_contenido_alter_ejercicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='tests_avanzados',
            field=models.JSONField(blank=True, help_text='Tests avanzados en formato JSON', null=True),
        ),
    ]
