# Generated by Django 5.2 on 2025-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_ejercicio_tests_avanzados'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='credito',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='intermedio', max_length=20),
        ),
    ]
