# Generated by Django 5.2 on 2025-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_historialevaluacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='creador_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
