# Generated by Django 5.2 on 2025-05-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_alter_ejercicio_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteevaluacion',
            name='tiempo_total_ms',
            field=models.BigIntegerField(blank=True, help_text='Tiempo total en milisegundos', null=True),
        ),
    ]
