# Generated by Django 5.2 on 2025-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_estudianteevaluacion_tiempo_total_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialevaluacion',
            name='tiempo_total_ms',
            field=models.BigIntegerField(blank=True, help_text='Tiempo total en milisegundos', null=True),
        ),
    ]
