# Generated by Django 5.2 on 2025-06-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_historialevaluacion_tiempo_total_ms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Clave de configuración', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Valor de configuración (JSON)')),
                ('description', models.CharField(blank=True, help_text='Descripción de la configuración', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuraciones de Plataforma',
                'ordering': ['key'],
            },
        ),
    ]
