# Generated by Django 5.2 on 2025-06-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaejercicio',
            name='language_id',
            field=models.IntegerField(default=71, help_text='ID del lenguaje usado (Judge0)'),
        ),
    ]
