# Generated by Django 5.2 on 2025-06-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_respuestaejercicio_language_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaejercicio',
            name='language_id',
        ),
    ]
