# Generated by Django 5.2 on 2025-07-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0014_remove_respuestaejercicio_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones', to='evaluations.curso'),
        ),
    ]
