# Generated by Django 5.2 on 2025-07-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0015_alter_evaluacion_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestaejercicio',
            name='language_id',
            field=models.IntegerField(default=71, help_text='ID del lenguaje de programación usado'),
        ),
    ]
