# Generated by Django 5.2 on 2025-04-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_estado_userprofile_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categoria',
            field=models.CharField(choices=[('tecnologia_educativa', 'Tecnología Educativa'), ('ciencias', 'Ciencias'), ('humanidades', 'Humanidades'), ('arte', 'Arte y Cultura'), ('otros', 'Otros')], default='tecnologia_educativa', help_text='Categoría general de educación', max_length=30),
        ),
    ]
